name: FabioIssao
favicon: null
layout_spectrum: 0.25721
typography_spectrum: 0.3778
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d24ab'
    - '#ffffff'
    - '#fec524'
    - '#1fcfcb'
    - '#f6303e'
  brandStrength: 1
  lightness: 0.09989814832806587
  saturation: 0.024542898405343294
  rhythmicContrast: 0.75
purpose: []
